---
title: "Data Translation Project"
format: html
editor: visual
---

```{r}
# Load Necessary Packages
library(lubridate)
library(stringr)
library(tidyverse)
library(vtable)
library(fixest)

install.packages("ipumsr")
library(ipumsr)
```

```{r}
# Load Data
ddi <- read_ipums_ddi("cps_00002.xml")
Translation.data <- read_ipums_micro(ddi)

```

```{r}
vtable(Translation.data)
```

```{r}
# Convert the 'YEAR' column to numeric if necessary
Translation.data$YEAR <- as.numeric(Translation.data$YEAR)

# Delete data before 2015
Translation.data <- Translation.data[Translation.data$YEAR >= 2015, ]

# Print the resulting data frame
print(Translation.data)
```

```{r}
# Filter the 'Translation.data' dataset based on 'IND' column
filtered_data <- Translation.data %>%
  filter(IND >= 4000 & IND <= 6000)

# Print the resulting filtered dataset
print(filtered_data)
```

```{r}
# Filter the 'Translation.data' dataset based on 'IND' and 'EMPSTAT' columns
filtered_data <- Translation.data %>%
  filter(IND == "retail" & EMPSTAT == "01")

# Calculate the total number of employed individuals in the retail industry
total_employed <- sum(filtered_data$EMPLOYMENT)

# Print the total number of employed individuals in the retail industry
print(total_employed)

```

```{r}
# Mutate Data and add Column for Employment share by industry, per month, and a Cutoff Variable at 3.11.20

```
